@startuml
package "com.matriculas.services" {

    class Usuario {
        - String nome
        - String login
        - String senha
    }

    class Aluno extends Usuario {
        - String matricula
        - ArrayList<Disciplina> disciplinasInscritas
        + matricularDisciplina(Disciplina disciplina)
        + cancelarDisciplina(Disciplina disciplina)
        + consultarDisciplina(Disciplina disciplina)
        + pagarCobranca()
    }

    class Professor extends Usuario {
        - String matricula
        - ArrayList<Disciplina> disciplinasLecionadas
        + consultarAlunosMatriculados(): ArrayList<Aluno>
    }

    class Secretaria extends Usuario {
        + gerarCurriculo()
        + manterDisciplina()
        + manterProfessor()
        + manterAluno()
    }

    class Curso {
        - String nome
        - Integer creditos
        - ArrayList<Disciplina> disciplinasCurso
        + adicionarDisciplina(Disciplina disciplina)
    }

    class Disciplina {
        - String nome
        - Integer creditos
        - Integer maximoAlunos = 60
        - Integer minimoAlunos = 3
        - TipoDisciplina tipoDisciplina
        + verificarStatus()
        + cancelarDisciplina()
    }

    enum TipoDisciplina {
        OBRIGATORIA, OPTATIVA
    }

    class Universidade {
        - String nome
        - ArrayList<Curso> cursosUniversidade
    }

    Universidade "1" --> "0..*" Curso
    Curso "1" --> "0..*" Disciplina
    Disciplina "0..*" --> "1" Aluno : inscrito
    Disciplina "0..*" --> "1" Professor : leciona
}

@enduml
